import { createElement } from 'inferno-create-element';
import { Link } from 'inferno-router';
import { Badge } from '../../../ui/Badge';

export function BlazecnIntro() {
  return createElement('div', { className: 'space-y-8' },
    // Hero
    createElement('div', null,
      createElement('div', { className: 'flex items-center gap-3 mb-2' },
        createElement('span', { className: 'text-3xl' }, '\u26A1'),
        createElement('h1', { className: 'text-3xl font-bold tracking-tight' }, 'Blazecn'),
      ),
      createElement('p', { className: 'text-muted-foreground max-w-2xl mb-4' },
        'A shadcn/ui-compatible component library for InfernoJS. Same design tokens, same class strings, zero React dependency. Built for speed.',
      ),
      createElement('div', { className: 'flex flex-wrap gap-2 mb-4' },
        createElement(Badge, null, 'InfernoJS'),
        createElement(Badge, { variant: 'secondary' }, 'Tailwind CSS v4'),
        createElement(Badge, { variant: 'secondary' }, 'class-variance-authority'),
        createElement(Badge, { variant: 'outline' }, 'MIT License'),
      ),
    ),

    // Overview
    createElement('div', { className: 'space-y-4' },
      createElement('h2', { className: 'text-xl font-bold tracking-tight' }, 'Overview'),
      createElement('p', { className: 'text-sm text-muted-foreground' },
        'Blazecn follows the shadcn philosophy \u2014 you own the code. Copy the components you need into your project. Every component is a single file with only cn() as a local dependency.',
      ),
      createElement('div', { className: 'grid grid-cols-1 sm:grid-cols-3 gap-4' },
        ...[
          { title: '38 Components', desc: 'Buttons, forms, overlays, data display, navigation, and layout primitives.' },
          { title: 'InfernoJS Native', desc: 'Pure createElement calls. No JSX runtime, no React, no hooks. Class components for state.' },
          { title: 'Tailwind v4', desc: 'OKLCH design tokens, CSS custom properties, @theme inline bridge. Light + dark themes.' },
        ].map((item) =>
          createElement('div', {
            key: item.title,
            className: 'rounded-lg border border-border p-4',
          },
            createElement('p', { className: 'text-sm font-semibold mb-1' }, item.title),
            createElement('p', { className: 'text-xs text-muted-foreground' }, item.desc),
          ),
        ),
      ),
    ),

    // Component list
    createElement('div', { className: 'space-y-4' },
      createElement('h2', { className: 'text-xl font-bold tracking-tight' }, 'Components'),
      createElement('p', { className: 'text-sm text-muted-foreground' },
        'Browse individual component documentation from the sidebar, or jump to a category:',
      ),
      createElement('div', { className: 'grid grid-cols-2 sm:grid-cols-4 gap-2' },
        ...[
          { label: 'Accordion', path: '/docs/blazecn/accordion' },
          { label: 'Alert', path: '/docs/blazecn/alert' },
          { label: 'Alert Dialog', path: '/docs/blazecn/alert-dialog' },
          { label: 'Aspect Ratio', path: '/docs/blazecn/aspect-ratio' },
          { label: 'Avatar', path: '/docs/blazecn/avatar' },
          { label: 'Badge', path: '/docs/blazecn/badge' },
          { label: 'Breadcrumb', path: '/docs/blazecn/breadcrumb' },
          { label: 'Button', path: '/docs/blazecn/button' },
          { label: 'Button Group', path: '/docs/blazecn/button-group' },
          { label: 'Card', path: '/docs/blazecn/card' },
          { label: 'Carousel', path: '/docs/blazecn/carousel' },
          { label: 'Checkbox', path: '/docs/blazecn/checkbox' },
          { label: 'Collapsible', path: '/docs/blazecn/collapsible' },
          { label: 'Combobox', path: '/docs/blazecn/combobox' },
          { label: 'Command', path: '/docs/blazecn/command' },
          { label: 'Context Menu', path: '/docs/blazecn/context-menu' },
          { label: 'Dialog', path: '/docs/blazecn/dialog' },
          { label: 'Drawer', path: '/docs/blazecn/drawer' },
          { label: 'Dropdown Menu', path: '/docs/blazecn/dropdown-menu' },
          { label: 'Empty', path: '/docs/blazecn/empty' },
          { label: 'Hover Card', path: '/docs/blazecn/hover-card' },
          { label: 'Input', path: '/docs/blazecn/input' },
          { label: 'Input OTP', path: '/docs/blazecn/input-otp' },
          { label: 'Kbd', path: '/docs/blazecn/kbd' },
          { label: 'Label', path: '/docs/blazecn/label' },
          { label: 'Menubar', path: '/docs/blazecn/menubar' },
          { label: 'Navigation Menu', path: '/docs/blazecn/navigation-menu' },
          { label: 'Pagination', path: '/docs/blazecn/pagination' },
          { label: 'Popover', path: '/docs/blazecn/popover' },
          { label: 'Progress', path: '/docs/blazecn/progress' },
          { label: 'Radio Group', path: '/docs/blazecn/radio-group' },
          { label: 'Resizable', path: '/docs/blazecn/resizable' },
          { label: 'Scroll Area', path: '/docs/blazecn/scroll-area' },
          { label: 'Select', path: '/docs/blazecn/select' },
          { label: 'Separator', path: '/docs/blazecn/separator' },
          { label: 'Sheet', path: '/docs/blazecn/sheet' },
          { label: 'Skeleton', path: '/docs/blazecn/skeleton' },
          { label: 'Slider', path: '/docs/blazecn/slider' },
          { label: 'Sonner', path: '/docs/blazecn/toast' },
          { label: 'Spinner', path: '/docs/blazecn/spinner' },
          { label: 'Switch', path: '/docs/blazecn/switch' },
          { label: 'Table', path: '/docs/blazecn/table' },
          { label: 'Tabs', path: '/docs/blazecn/tabs' },
          { label: 'Textarea', path: '/docs/blazecn/textarea' },
          { label: 'Themes', path: '/docs/blazecn/theme-toggle' },
          { label: 'Toggle', path: '/docs/blazecn/toggle' },
          { label: 'Toggle Group', path: '/docs/blazecn/toggle-group' },
          { label: 'Tooltip', path: '/docs/blazecn/tooltip' },
          { label: 'Typography', path: '/docs/blazecn/typography' },
        ].map((item) =>
          createElement(Link, {
            key: item.label,
            to: item.path,
            className: 'rounded-md border border-border px-3 py-2 text-sm text-muted-foreground hover:text-foreground hover:bg-accent/50 transition-colors',
          }, item.label),
        ),
      ),
    ),
  );
}
