import { createElement } from 'inferno-create-element';
import { PageHeader, SectionHeading, DemoBox, CodeBlock, PropTable } from '../_helpers';
import {
  NavigationMenu, NavigationMenuList, NavigationMenuItem,
  NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink,
} from '../../../ui/NavigationMenu';

export function NavigationMenuPage() {
  return createElement('div', { className: 'space-y-10' },
    createElement(PageHeader, {
      title: 'Navigation Menu',
      description: 'A collection of links for navigating websites, with support for dropdown panels.',
    }),

    // Demo
    createElement(SectionHeading, { id: 'demo' }, 'Demo'),
    createElement(DemoBox, { className: 'block p-8' },
      createElement(NavigationMenu, null,
        createElement(NavigationMenuList, null,
          createElement(NavigationMenuItem, null,
            createElement(NavigationMenuTrigger, null, 'Getting Started'),
            createElement(NavigationMenuContent, { className: 'w-[400px]' },
              createElement('ul', { className: 'grid gap-3 p-4 md:grid-cols-2' },
                createElement('li', null,
                  createElement(NavigationMenuLink, { href: '#' },
                    createElement('div', { className: 'text-sm font-medium leading-none' }, 'Introduction'),
                    createElement('p', { className: 'line-clamp-2 text-sm leading-snug text-muted-foreground mt-1' },
                      'Re-usable components built with Inferno and Tailwind CSS.',
                    ),
                  ),
                ),
                createElement('li', null,
                  createElement(NavigationMenuLink, { href: '#' },
                    createElement('div', { className: 'text-sm font-medium leading-none' }, 'Installation'),
                    createElement('p', { className: 'line-clamp-2 text-sm leading-snug text-muted-foreground mt-1' },
                      'How to install dependencies and structure your app.',
                    ),
                  ),
                ),
                createElement('li', null,
                  createElement(NavigationMenuLink, { href: '#' },
                    createElement('div', { className: 'text-sm font-medium leading-none' }, 'Typography'),
                    createElement('p', { className: 'line-clamp-2 text-sm leading-snug text-muted-foreground mt-1' },
                      'Styles for headings, paragraphs, lists, and more.',
                    ),
                  ),
                ),
                createElement('li', null,
                  createElement(NavigationMenuLink, { href: '#' },
                    createElement('div', { className: 'text-sm font-medium leading-none' }, 'Theming'),
                    createElement('p', { className: 'line-clamp-2 text-sm leading-snug text-muted-foreground mt-1' },
                      'Customize colors, fonts, and other design tokens.',
                    ),
                  ),
                ),
              ),
            ),
          ),
          createElement(NavigationMenuItem, null,
            createElement(NavigationMenuTrigger, null, 'Components'),
            createElement(NavigationMenuContent, { className: 'w-[400px]' },
              createElement('ul', { className: 'grid gap-3 p-4 md:grid-cols-2' },
                createElement('li', null,
                  createElement(NavigationMenuLink, { href: '#' },
                    createElement('div', { className: 'text-sm font-medium leading-none' }, 'Alert Dialog'),
                    createElement('p', { className: 'line-clamp-2 text-sm leading-snug text-muted-foreground mt-1' },
                      'A modal dialog that interrupts the user.',
                    ),
                  ),
                ),
                createElement('li', null,
                  createElement(NavigationMenuLink, { href: '#' },
                    createElement('div', { className: 'text-sm font-medium leading-none' }, 'Hover Card'),
                    createElement('p', { className: 'line-clamp-2 text-sm leading-snug text-muted-foreground mt-1' },
                      'For sighted users to preview content behind a link.',
                    ),
                  ),
                ),
                createElement('li', null,
                  createElement(NavigationMenuLink, { href: '#' },
                    createElement('div', { className: 'text-sm font-medium leading-none' }, 'Tabs'),
                    createElement('p', { className: 'line-clamp-2 text-sm leading-snug text-muted-foreground mt-1' },
                      'A set of layered sections of content.',
                    ),
                  ),
                ),
                createElement('li', null,
                  createElement(NavigationMenuLink, { href: '#' },
                    createElement('div', { className: 'text-sm font-medium leading-none' }, 'Tooltip'),
                    createElement('p', { className: 'line-clamp-2 text-sm leading-snug text-muted-foreground mt-1' },
                      'A popup that displays information on hover.',
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),

    // Usage
    createElement(SectionHeading, { id: 'usage' }, 'Usage'),
    createElement(CodeBlock, { code: `import {
  NavigationMenu, NavigationMenuList, NavigationMenuItem,
  NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink,
} from '@/ui/NavigationMenu'

createElement(NavigationMenu, null,
  createElement(NavigationMenuList, null,
    createElement(NavigationMenuItem, null,
      createElement(NavigationMenuTrigger, null, 'Getting Started'),
      createElement(NavigationMenuContent, null,
        createElement(NavigationMenuLink, { href: '/docs' }, 'Introduction'),
      ),
    ),
  ),
)` }),

    // Props
    createElement(SectionHeading, { id: 'props' }, 'Props'),
    createElement('h3', { className: 'text-sm font-semibold mb-2' }, 'NavigationMenuLink'),
    createElement(PropTable, {
      rows: [
        { prop: 'href', type: 'string', default: '\u2014' },
        { prop: 'onClick', type: '(e: Event) => void', default: '\u2014' },
      ],
    }),
  );
}
